- name: Module for uploading and upgrading firmware using vManage
  connection: local
  hosts: localhost
  gather_facts: False
  vars_files:
  - variables.yml
  - vault.yml

  tasks:
  - debug:
      msg: "** Start of Workflow **"

  - name: Firmware_Upload
    viptela_command:
      user: '{{ user }}'
      user_pass: '{{ pass }}'
      vmanage_server: "{{ vmanage_server }}"
      filename: 'viptela-18.2.0-mips64.tar.gz'
      action: 'firmware_upload'
    register: upload

  - debug:
      msg: "** End of Workflow **"
