- name: Module for uploading and upgrading firmware using vManage
  connection: local
  hosts: localhost
  gather_facts: False
  vars_files:
  - variables.yml

  tasks:
  - debug:
      msg: "** Start of Workflow **"

  - set_fact:
      ip_address: '1.1.1.10'

  - set_fact:
      version: '17.2.5'

  - set_fact:
      vmanage_server: '172.16.130.171'

  - set_fact:
      timeout: 30

  - name: Get_UUID
    viptela_command:
      user: 'admin2'
      user_pass: 'admin2'
      vmanage_server: "{{ vmanage_server }}"
      device_type: 'vedges'
      action: 'get_all_devices'
    register: devices

  - set_fact:
      device_uuid={{ devices.results | selectattr('deviceId', 'equalto', ip_address) |
        map(attribute='uuid') | list }}

  - name: Upgrade_Software
    viptela_command:
      user: 'admin2'
      user_pass: 'admin2'
      vmanage_server: "{{ vmanage_server }}"
      version: "{{ version }}"
      URL: 'vmanage'
      #device_type: 'vedges'
      action: 'upgrade'
      ip_address: "{{ ip_address }}"
      device_uuid: "{{ device_uuid[0] }}"
    register: upgrade

  - name: Check_Upgrade_Status
    viptela_command:
      user: 'admin2'
      user_pass: 'admin2'
      vmanage_server: "{{ vmanage_server }}"
      URL: "{{ upgrade.results }}"
      action: 'check_status'
    register: check_status
    retries: "{{ timeout * 6 }}"
    delay: 10
    until: ( check_status.results[0].statusId=="success" ) or
           ( check_status.results[0].statusId=="skipped" )

  - debug:
      msg: "** End of Workflow **"

