- name: Module for uploading and upgrading firmware using vManage
  connection: local
  hosts: localhost
  gather_facts: False
  vars_files:
  - variables.yml
  - vault.yml

  tasks:
  - debug:
      msg: "** Start of Workflow **"

  - name: Get_UUID
    viptela_command:
      user: '{{ user }}'
      user_pass: '{{ pass }}'
      vmanage_server: "{{ vmanage_server }}"
      device_type: 'vedges'
      action: 'get_all_devices'
    register: devices

  - set_fact:
      device_uuid={{ devices.results | selectattr('deviceId', 'equalto', ip_address) |
        map(attribute='uuid') | list }}

  - name: Get_Running_Config
    viptela_command:
      user: '{{ user }}'
      user_pass: '{{ pass }}'
      device_uuid: "{{ device_uuid[0] }}"
      vmanage_server: "{{ vmanage_server }}"
      action: 'get_running_config'
    register: results

  - debug:
      msg: "{{ results }}"

  - name: Test_command - Check Firmware
    viptela_command:
      user: '{{ user }}'
      user_pass: '{{ pass }}'
      vmanage_server: "{{ vmanage_server }}"
      action: 'check_firmware'
    register: results

  - set_fact:
      device_firmwares={{ results.results | selectattr('system-ip', 'equalto', ip_address) |
        map(attribute='availableVersions') | list }}

  - fail:
       msg: '{{ "Version " + version + " already installed" }}'
    when: version in device_firmwares[0]

  - debug:
      msg: "{{ results }}"

  - debug:
      msg: "** End of Workflow **"
